export const products = [
  {
    name: "K-Swiss V8 - Masculino",
    category: "Roupas",
    price: 100,
    price_old: 200,
    discount: "30% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Roupas",
    price: 100,
    price_old: 200,
    discount: "30% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
];
