export const products = [
  {
    id: 1,
    name: "K-Swiss V8 - Masculino",
    category: "Roupas",
    price: 100,
    price_old: 200,
    discount: "30% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 2,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    imageSrc: "tenis_product.svg",
  },
  {
    id: 3,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 4,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 5,
    name: "K-Swiss V8 - Masculino",
    category: "Roupas",
    price: 100,
    price_old: 200,
    discount: "30% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 6,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    imageSrc: "tenis_product.svg",
  },
  {
    id: 7,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 8,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
];
