export const products = [
  {
    id: 1,
    name: "K-Swiss V8 - Masculino",
    category: "Roupas",
    price: 100,
    price_old: 200,
    discount: "30% OFF",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 2,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 3,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 4,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 5,
    name: "K-Swiss V8 - Masculino",
    category: "Roupas",
    price: 100,
    price_old: 200,
    discount: "30% OFF",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 6,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 7,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    discount: "15% OFF",
    imageSrc: "tenis_product.svg",
  },
  {
    id: 8,
    name: "K-Swiss V8 - Masculino",
    category: "Tênis",
    price: 100,
    price_old: 200,
    discount: "15% OFF",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
    imageSrc: "tenis_product.svg",
  },
];
